name: Docker Image CI

on:
  push:
    branches: '**'
    tags: 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - run: docker build . --file Dockerfile --tag docker-nginx-vfbiri:${GITHUB_REF#refs/heads/}
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@v1.1.2
      with:
        name: rcourt/docker-nginx-vfbiri
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
